add share export locations requests and models
sapcc/fog-openstack pull request #12
Opened 2016-11-28 16:12 UTC by andypf

@Carthaca Please take a look

2016-11-29 07:22 UTC, Carthaca commented
maybe comment or make sure technically (have a look at the method `microversion_newer_than?`) that this only works since microversion 2.9 (and the preferred attribute only since 2.14)

2016-11-29 07:23 UTC, Carthaca requested changes
maybe comment or make sure technically (have a look at the method microversion_newer_than?) that this only works since microversion 2.9 (and the preferred attribute only since 2.14)

2016-11-29 07:23 UTC, Carthaca commented on lib/fog/shared_file_system/openstack/requests/get_share_export_location.rb
> +          share_export_location = data[:share_export_location]
would you please add some Mock data in `lib/fog/shared_file_system/openstack.rb`?

2016-11-29 07:23 UTC, Carthaca commented on lib/fog/shared_file_system/openstack/requests/list_share_export_locations.rb
> +          locations = data[:export_locations]
same as above

2016-12-05 10:52 UTC, andypf commented
@Carthaca Please take a look

2016-12-05 12:23 UTC, Carthaca commented on lib/fog/shared_file_system/openstack/requests/get_share_export_location.rb
> +          share_export_location = data[:share_export_location]
I suggest changing to `data[:export_locations].first`

2016-12-05 12:25 UTC, Carthaca requested changes

2016-12-05 12:25 UTC, Carthaca commented on lib/fog/shared_file_system/openstack.rb
> +                  "path": "10.254.0.3:/shares/share-e1c2d35e-fe67-4028-ad7a-45f668732b1d",
please change to hash-rocket syntax, i.e. `=>` instead of `:`

2016-12-05 13:28 UTC, Carthaca approved these changes

2016-12-05 13:35 UTC, merged