add os_interfaces to compute
sapcc/fog-openstack pull request #20
Opened 2017-01-10 15:05 UTC by andypf

@Carthaca: please take a look

2017-01-10 15:34 UTC, Carthaca requested changes
and I'm not sure about the `expects` i.e. the response status - api ref says otherwise, but we had occasions where it was good to allow more

2017-01-10 15:34 UTC, Carthaca commented on lib/fog/compute/openstack/requests/create_os_interface.rb
> +              'net_id' => options[:net_id]
- `net_id`is optional
- and it is not allowed if `port_id` is specified

2017-01-10 15:34 UTC, Carthaca commented on lib/fog/compute/openstack/models/os_interface.rb
> +        attribute :fixed_ips, type: :array
hash rocket syntax pls, i.e. `:type => :array`

2017-01-10 15:34 UTC, Carthaca commented on lib/fog/compute/openstack/models/os_interfaces.rb
> +require 'fog/compute/openstack/models/network'
c&p error: `..os_interface`

2017-01-10 15:34 UTC, Carthaca commented on lib/fog/compute/openstack/requests/delete_os_interface.rb
> +            :path    => "/servers/#{server_id}/os-interface/#{port_id}"
extra `/` at the beginning

2017-01-10 15:36 UTC, Carthaca commented
and to get it upstream we would at least need the mock implementation and unit tests - even better vcr

2017-01-10 16:05 UTC, Carthaca commented on lib/fog/compute/openstack.rb
> +                    "fixed_ips": [
and again the need for hash rockets to keep the ruby 1.9 support 🚀

2017-01-11 08:46 UTC, andypf reviewed
All changes have been implemented

2017-01-11 09:10 UTC, merged